### ISSUE TITLE
The property 'Authority' cannot be found on this object.

### ISSUE THREAD

**Issue by HAL377** [AzureAD/MSAL.PS#45] opened 2021-12-03 17:52 UTC
Hi,

With version 4.21.0.1 I was able to run this without any issues 

Get-MsalToken -TenantId $TenantId -ClientId $ClientId -Scopes "User.ReadWrite.All","Directory.ReadWrite.All" -UserCredential $Credentials

but with the release 4.37.0.0 I get suddenly this error:

 **_The property 'Authority' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\MSAL.PS\4.37.0.0\Get-MsalToken.ps1:338 char:38
+ ... TenantId) { [void] $AquireTokenParameters.WithAuthority(('https://{0} ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict_**

The ClientID is that of Microsoft Graph PowerShell (14d82eec-204b-4c2f-b7e8-296a70dab67e), and credentials are captured with Get-Credential.

I did the test within the same PS Session, same variables, simply changing the modules with -RequiredVersion during the import and I get to the error.

My Credential is a federated user identity.

Thanks for your feedback

Sincerely,
Tonino Bruno
ENGIE SA

**Comment by HAL377** [comment] 2021-12-03 19:42
If I remove the TenantID switch it work with the latest version (4.37.0.0), but the same does not work on the 4.21.0.1 as I get the following error: Get-MsalToken : AADSTS9001023: The grant type is not supported over the /common or /consumers endpoints. Please use the /organizations or tenant-specific endpoint.

Adding the -TenantID detail should not result in this error I think and feels like a bug...

**Comment by EMarcais** [comment] 2021-12-06 09:33
Hi Hal37,

Had the same issue using this line:
$Token = (Get-MsalToken -ClientId ($Config.ScriptMainConfig.TenantConfig.clientId) -TenantId ($Config.ScriptMainConfig.TenantConfig.tenantId) -ClientCertificate $thumbPrint).AccessToken

To resolve this, while waiting for an answer from Repo's maintainer, I opened the file Get-MsalToken.ps1 in the module folder and just commented the elseif line: 
``` Powershell
"*" {
                if ($AzureCloudInstance -and $TenantId) { [void] $AquireTokenParameters.WithAuthority($AzureCloudInstance, $TenantId) }
                elseif ($AzureCloudInstance) { [void] $AquireTokenParameters.WithAuthority($AzureCloudInstance, 'common') }
                #elseif ($TenantId) { [void] $AquireTokenParameters.WithAuthority(('https://{0}' -f $ClientApplication.AppConfig.Authority.AuthorityInfo.Host), $TenantId) }
                if ($Authority) { [void] $AquireTokenParameters.WithAuthority($Authority.AbsoluteUri) }
```

**Comment by abgreg** [comment] 2021-12-06 23:31
+1 Same for me. (Context: Internal Microsoft / Office tooling) Goods news: I'm the only one on my team reproing this so far. Bad news: This is a pretty blocking issue for me - reproing across accounts, machines, and scenarios.

**Comment by ioamnesia** [comment] 2021-12-14 02:29
Ok, digging further, it looks like there was a change to the Microsoft.Identity.Client package that modified the members of ClientApplicationBase to put an Authority member and nest the existing AuthorityInfo member under that. Check your installed version using Get-Package Microsoft.Identity.Client. I had 4.16.0 installed and encountered this same error.

**Comment by ioamnesia** [comment] 2021-12-14 02:34
We need to get this module updated in such a way that it ensures that a version of Microsoft.Identity.Client that is compatible is installed.

**Comment by ioamnesia** [comment] 2021-12-14 02:52
@HAL377  @EMarcais @abgreg 

I was able to fix this by uninstalling any older nuget packages for Microsoft.Identity.Client and then uninstalling and reinstalling the MSAL.PS module.

**Comment by abgreg** [comment] 2021-12-14 21:17
Interesting... I don't think that I have such a package installed?

```
PS C:\WINDOWS\system32> Get-Package Microsoft.Identity.Client
Get-Package : No package found for 'Microsoft.Identity.Client'.
```

**Comment by HAL377** [comment] 2021-12-15 16:00
Hi,

I tried your suggestion to add those DLL's directly but it did not change on my end... But perhaps I did not load the correct ones?

MSAL.PS\4.37.0.0\Microsoft.Identity.Client.4.37.0\net45\Microsoft.Identity.Client.dll
MSAL.PS\4.37.0.0\Microsoft.Identity.Client.Desktop.4.37.0\net461\Microsoft.Identity.Client.Desktop.dll

![image](https://user-images.githubusercontent.com/56118373/146220744-db45bac6-5070-4674-8e82-2cc05319b7a5.png)

**Comment by jasoth** [comment] 2021-12-17 21:06
For those who are able to reproduce this, do you have any profile scripts that auto-run or other modules imported before importing MSAL.PS? MSAL.PS will allow you to use an old version of the dll libraries if they are already imported into the session. This is a common issue with the Az modules. MSAL.PS should prompt you though when this dll conflict occurs allowing you to proceed but warning you that some functionality might not work correctly.

**Comment by JBines** [comment] 2022-01-13 16:45
Umm... Seems like github has been updated but PowershellGet hasn't

I replaced line 338 in the module with below and it works for me

elseif ($TenantId) { [void] $AquireTokenParameters.WithAuthority(('https://{0}' -f $ClientApplication.AppConfig.AuthorityInfo.Host), $TenantId) }

![image](https://user-images.githubusercontent.com/40031426/149371537-52f1a69f-ba58-42b4-9d87-00508871c1b2.png)

https://github.com/ioamnesia/MSAL.PS/commit/abdea2b61f147273466ed3015dcded893ee7acdc

**Comment by jakubmank** [comment] 2022-02-11 15:20
Got the same problem in my script. The reason was `ExchangeOnlineManagement` module. One of its cmdlet was called before `Get-MsalToken`  therefore the `MSAL.PS` module was not imported as first. 
I had to explictly put `Import-Module MSAL.PS` at the top of file (or just before using any other cmdlet which could load different module).

**Comment by mmascolino** [comment] 2022-02-25 16:46
I too ran into the issue with the collision of ExchangeOnlineManagement and Get-MSALToken.  The simple solution was to use Get-MSALToken in a fresh PowerShell session.

**Comment by mortenlerudjordet** [comment] 2022-03-11 07:51
The same issue also exist using MSAL.PS with the MicrosoftTeams module.
At the moment I'm using version 4.36.1.2 of MSAL.PS without issue, but new version does not work.

I'm using MSAL with SP and a AAD user for delegated permissions.

In a fresh powershell session i need to run:
```
Import-Module MSAL.PS -MaximumVersion 4.36.1.2 -ErrorAction Continue -ErrorVariable oErr -Verbose:$false
if($oErr)
{
    Write-Error -Message "Failed to import supporten module version of: MSAL.PS" -ErrorAction Stop
}

Import-Module MicrosoftTeams -MaximumVersion 3.0.0 -ErrorAction Continue -ErrorVariable oErr -Verbose:$false
if($oErr)
{
    Write-Error -Message "Failed to import supporten module version of: MicrosoftTeams" -ErrorAction Stop
}
```

**Comment by mortenlerudjordet** [comment] 2022-03-12 10:26
I added the following code instead on line 338, and this seems to do the trick with object structure conflicts.

```
elseif ($TenantId) {
	if( Get-Member -InputObject $ClientApplication.AppConfig -Name "AuthorityInfo" -MemberType Properties )
	{
		[void] $AquireTokenParameters.WithAuthority(('https://{0}' -f $ClientApplication.AppConfig.AuthorityInfo.Host), $TenantId)
	}
	else
	{
		[void] $AquireTokenParameters.WithAuthority(('https://{0}' -f $ClientApplication.AppConfig.Authority.AuthorityInfo.Host), $TenantId)
	}
}
```

**Comment by o-l-a-v** [comment] 2022-03-21 09:47
Could it be related to assembly dependency conflicts?

* https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.2
* https://github.com/PowerShell/PowerShell/issues/2083

I was checking out MSAL.PS today for replacing following code for generating access token with app id and secret only:


Might be helpful for others in same situation. Until MSAL.PS get's up and running again.

```powershell
# Settings
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12

# Assets
$AppRegistration = [pscredential](Get-Credential -Message 'App Id and secret')
$TenantInitialDomain = [string] '<your_initial_domain>.onmicrosoft.com'
$TenantId = [string](
    (Invoke-RestMethod -Uri ('https://login.microsoftonline.com/{0}/.well-known/openid-configuration'-f$TenantInitialDomain) -Method 'Get').'userinfo_endpoint'.Split('/')[3]
)
$Body = [hashtable]@{
    'client_id'     = $AppRegistration.'Username'
    'client_secret' = $AppRegistration.GetNetworkCredential().'Password'
    'scope'         = 'https://graph.microsoft.com/.default'
    'grant_type'    = 'client_credentials'
}

# Get access token
$AccessToken = Invoke-RestMethod -Method 'Post' ('https://login.microsoftonline.com/{0}/oauth2/v2.0/token' -f $TenantId) -Body $Body

# Example use - Connect with Microsoft.Graph.Authentication
$null = Connect-MgGraph -ContextScope 'Process' -AccessToken $AccessToken.'access_token'
```

**Comment by mortenlerudjordet** [comment] 2022-03-21 11:10
I'm running MSAL.PS in one location for both 5.1 and 7.2.
Usually when the error crops up is when I switch between the runtimes, though have not spent to much time understanding where the problem comes from.

I did a debug through VSCode and saw that the $ClientApplication substructure was a bit different when it errors out.
Guess that might be because different Microsoft.Identity.Client.dll are loaded into 5.1 and 7.2.

Compensating for the object structure difference, I did not get any other errors and the token was received as expected.

**Comment by err-unknown-username** [comment] 2022-03-21 21:43
@mortenlerudjordet your post as of 9 days ago (Mar-12?) looks like a good work around. 

@jasoth / @apurvghai : do you know what the release process for this project is?

**Comment by agrecaBAS** [comment] 2022-04-19 01:05
On the off chance is anyone having this issue after importing Graph modules? I just discovered that I get this error if I run any of the following commands before running Get-MSALToken. I'm assuming it's going to be any Graph modules though.

Select-MgProfile -Name "beta"

Import-Module Microsoft.Graph.Users
Import-Module Microsoft.Graph.Identity.Signins
Import-Module Microsoft.Graph.Authentication

If I run the Get-MSALToken before importing the other modules, I don't get the error.

**Comment by mortenlerudjordet** [comment] 2022-04-19 05:38
@agrecaBAS, I import MSAL before graph and that seems to not give me the error

**Comment by jasoth** [comment] 2022-06-29 13:52
This error and numerous others can happen when the DLLs included with MSAL.PS cannot be loaded due to a conflict with another DLL loaded in the current PowerShell session, often from another module like Azure or Exchange Online Admin Shell.

You should see the following prompt during import when this occurs and as the message indicates, "Some module functionality will not work."
```
Ignore assembly conflict and continue importing module?
Some module functionality will not work.
[Y] Yes  [N] No  [?] Help (default is "N"):
```

As a workaround, I would suggest ensuring that the MSAL.PS module is loaded into the PowerShell session first before any other modules. There is a fix to this but it would require significant rework of the MSAL.PS module in C# so no guarantee this will be addressed anytime soon, if ever.

**Closed by jasoth** 2022-06-29 13:52 UTC

**Comment by DMahalko** [comment] 2022-08-16 09:45
> I was checking out MSAL.PS today for replacing following code for generating access token with app id and secret only:
> [....]
> But got the "The property 'Authority' cannot be found on this object" error. I added the code here as it might be helpful for others in same situation. Until MSAL.PS get's up and running again.

Can you explain why you care about MSAL.PS if the workaround code in your comment does the job required? 

```
$AppID = ...
$AppSecret = ...
$TenantID = ...
$Body = [hashtable]@{
    'client_id'     = $AppID
    'client_secret' = $AppSecret
    'scope'         = 'https://graph.microsoft.com/.default'
    'grant_type'    = 'client_credentials'
}
$AccessToken = Invoke-RestMethod -Method 'Post' `
  ('https://login.microsoftonline.com/{0}/oauth2/v2.0/token' `
  -f $TenantId) -Body $Body

# Connect with Microsoft.Graph.Authentication
Connect-MgGraph -AccessToken $AccessToken.'access_token'
```
This works, and I don't need to load any additional modules. I have no idea what is "wrong" with doing this vs using Get-MsalToken..

**Comment by o-l-a-v** [comment] 2022-08-16 13:37
@DMahalko 

Because 1) IMO this functionality should work in such a module, and 2) I'd rather update an module than code.

**Comment by Zachbanderson** [comment] 2022-10-14 16:05
I know this thread has been closed for a while, but installing the module first thing was an unreliable fix due to my environment. Adding a "-AzureCloudInstance 1" to the function call fixed it.

So my code became:
`Get-MsalToken -ClientId $ClientId -TenantId $TenantId -ClientSecret $ClientSecret -AzureCloudInstance 1`

[Here is a link to how the AzureCloudInstance parameter works. It's in C# but it translates to PowerShell too.](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.azurecloudinstance?view=azure-dotnet-preview)

**Comment by clearchaos3** [comment] 2022-10-23 18:20
> I know this thread has been closed for a while, but installing the module first thing was an unreliable fix due to my environment. Adding a "-AzureCloudInstance 1" to the function call fixed it.
> 
> So my code became: `Get-MsalToken -ClientId $ClientId -TenantId $TenantId -ClientSecret $ClientSecret -AzureCloudInstance 1`
> 
> [Here is a link to how the AzureCloudInstance parameter works. It's in C# but it translates to PowerShell too.](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.azurecloudinstance?view=azure-dotnet-preview)

My man, you are a life saver! This worked for me as well. Thank you.
