### ISSUE TITLE
Get-MsalToken with Client Certificate fails on Windows PowerShell 5.1

### ISSUE THREAD

**Issue by darrenjrobinson** [AzureAD/MSAL.PS#15] opened 2020-08-06 23:46 UTC
The following syntax for Get-MSALToken on PowerShell 7.0.3 successfully returns an Access Token.

Get-MsalToken -ClientId $clientID -TenantId $tenantID -ClientCertificate $ClientCertificate 

However it fails on Windows PowerShell 5.1 (using MSAL.PS v 4.16.0.2). I've also tested pervious versions of the MSAL.PS Module ( 4.9.0.1, 4.10.0.2 and 4.14.0.1 ) and the same error is returned. The error returned is:
```
Invalid provider type specified.

At line:6 char:18
+ ... cessToken = Get-MsalToken -ClientId $clientID -TenantId $tenantID -Cl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (Microsoft.Ident...arameterBuilder:AcquireTokenForClientParameterBuilder) [Write-Error], CryptographicException
    + FullyQualifiedErrorId : GetMsalTokenFailureAuthenticationError,Get-MsalToken
```

Platform info
```
PS C:\Users\darrenjrobinson> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by jasoth** [comment] 2020-08-18 23:18
@darrenjrobinson That command works for me. What is the object type of the certificate variable you are providing?

```
PS C:\Users\jason> $ClientCertificate = (Get-ChildItem 'Cert:\CurrentUser\My\38E962BBCA768BA52EE9A997A1FEA32A811BD911') 
PS C:\Users\jason> $ClientCertificate.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     X509Certificate2                         System.Security.Cryptography.X509Certificates.X509Certifi...
```

**Comment by darrenjrobinson** [comment] 2020-08-18 23:23
It works for me in PowerShell 7.x but fails on Windows PowerShell 5.1 @jasoth 
ObjectType of the Cert is the same as you. 

![image](https://user-images.githubusercontent.com/384733/90574922-7db1c800-e1fd-11ea-8b02-d61f0aa50044.png)

**Comment by jasoth** [comment] 2020-08-18 23:37
The exception is occurring in the MSAL.NET library so the module is returning the inner exception as the error. Could it be a permission issue to the private key?
https://stackoverflow.com/questions/22581811/invalid-provider-type-specified-cryptographicexception-when-trying-to-load-pri

**Comment by darrenjrobinson** [comment] 2020-08-18 23:51
Interesting. If it was a permissions issue though I'd expect it to fail regardless of PS version as it is being used under the context of the same User in both v5.1 and v7. 
The same error is thrown under Administrative and User contexts (but only in PS v5.1). 
Here is it working in PS7 (Administrative context). 

![image](https://user-images.githubusercontent.com/384733/90576320-362d3b00-e201-11ea-9784-c5c1bd3f5df6.png)

**Comment by jasoth** [comment] 2020-10-12 20:53
@darrenjrobinson are you still having an issue with this? It appears to be some difference between how the certificate providers work on each platform so there probably isn't much I can do to help. I have not been able to reproduce the issue myself either. Let me know if you can help me repo. Otherwise, I will close this out.

**Comment by darrenjrobinson** [comment] 2020-10-17 04:58
@jasoth yes still having the issue. Have just updated to the latest MSAL.PS (4.21.0.1) module in WinPS5.1x and am getting the same error.

**Comment by jasoth** [comment] 2020-10-22 16:47
@darrenjrobinson Are you able to reproduce this with another certificate? Could you provide the steps used to get the certificate so I can attempt to repro as well?

**Comment by darrenjrobinson** [comment] 2020-10-28 01:40
Hey @jasoth ,

I've gone through to reproduce it again. 
Following the same process I detailed in the MSAL.PS with Certificates blogpost from a few months back [here](https://blog.darrenjrobinson.com/microsoft-graph-using-msal-with-powershell-and-certificate-authentication/)

## Generate Certificate
![image](https://user-images.githubusercontent.com/384733/97378919-a4842d00-1917-11eb-8119-150f203e6d48.png)

## Export the Certificate
![image](https://user-images.githubusercontent.com/384733/97379073-0775c400-1918-11eb-99d9-21e79d624e48.png)

## Convert the Certificate for upload to AAD
![image](https://user-images.githubusercontent.com/384733/97379282-92ef5500-1918-11eb-9e4b-3f49ef0bd93d.png)

## Upload to AAD App
![image](https://user-images.githubusercontent.com/384733/97379407-d9dd4a80-1918-11eb-8244-691d97af7373.png)
![image](https://user-images.githubusercontent.com/384733/97379470-fc6f6380-1918-11eb-8851-b28180cba429.png)

## Using the Cert for AuthN to the AAD App with PowerShell 7.0.3
![image](https://user-images.githubusercontent.com/384733/97379828-d6968e80-1919-11eb-96e3-aac18bcae518.png)

## Using the Cert for AuthN to the AAD App with Windows PowerShell 5.1
Interestingly I hadn't seen this particular expanded error message previously. 
![image](https://user-images.githubusercontent.com/384733/97379974-2f662700-191a-11eb-94f2-0b79e2451b23.png)

Here is the PSVersionTable from the error session above
![image](https://user-images.githubusercontent.com/384733/97380061-5b81a800-191a-11eb-9357-f3e813fbfb69.png)

And Module Version
![image](https://user-images.githubusercontent.com/384733/97380121-7a803a00-191a-11eb-8346-9b8cb26b93c9.png)

**Comment by SLeuthold** [comment] 2020-12-12 00:45
Following this thread! I'm getting the same issue.

**Comment by giani09** [comment] 2020-12-17 11:08
same here :(

**Comment by YuriySamorodov** [comment] 2020-12-18 00:42
Same =(

**Comment by tehKNi** [comment] 2021-01-14 08:12
Yeh, same. Following :-)

**Comment by jasoth** [comment] 2021-01-14 23:06
Thank you @darrenjrobinson for the step by step. Sorry for the delay. I was able to reproduce when I created the certificate using the command in your screenshot.

Based on the error message, I added `-KeySpec Signature` to the `New-SelfSignedCertificate` command when generating the certificate. That fixed the issue for me. That should technically be included on the cert anyway so it can be used to sign the JWT.

**Closed by jasoth** 2021-01-14 23:06 UTC

**Comment by DennisBergemann** [comment] 2022-06-03 05:22
I am late to the party, but as a special mention for followers or peoble that comes into the same issue as yours. 

The certificate above is lying under: **localmachine**,  so make sure you start your script/app with rights to access local machine otherwise use it in userstore.

**Comment by krzydoug** [comment] 2022-08-26 15:18
> Thank you @darrenjrobinson for the step by step. Sorry for the delay. I was able to reproduce when I created the certificate using the command in your screenshot.
> 
> Based on the error message, I added `-KeySpec Signature` to the `New-SelfSignedCertificate` command when generating the certificate. That fixed the issue for me. That should technically be included on the cert anyway so it can be used to sign the JWT.

So our existing cert just won't work in 5.1?

**Comment by JManDoo** [comment] 2022-08-31 15:39
![image](https://user-images.githubusercontent.com/21066923/187720180-8303b9e3-65cc-4f71-bc28-c91df60ec7fd.png)

Here is what solved it for me
Adding the user/service account to access the Private Key of the certificate

**Comment by iamkl00t** [comment] 2023-03-01 16:41
> I am late to the party, but as a special mention for followers or peoble that comes into the same issue as yours.
> 
> The certificate above is located under: **localmachine**, so make sure you start your script/app with rights to access local machine otherwise use it in userstore.

Thank you - this was exactly my problem - just needed to run powershell as admin 🤦🏻‍♂️
